### ISSUE TITLE
Error logging in to fogbugz with 2F authentication enabled

### ISSUE THREAD

**Issue by dcheese** [there4/fogbugz-php-cli#31]
When I try to login to our fogbugz server that has 2F authentication enabled, I'm getting the following error:

Login Error. Please check the url, username and password. Error: Two-factor authentication is enabled for this user

How do I login when 2F is enabled?

**Comment by craig-davis** [comment]
Hi @dcheese - I haven't run into this myself. From looking at [the docs](http://help.fogcreek.com/8447/how-to-get-a-fogbugz-xml-api-token), it looks like the logon command that this library uses [won't work with 2FA](http://help.fogcreek.com/10892/two-factor-authentication), but instead requires a token.

If you have time, a pull request would be very much appreciated.
